version: "3.9"
services:
  project-name:
    build: .
    ports: 
      - 3000:3000
    # Because this is mostly for the Dev Envoroment Preview, 'Volume' is not used
    # .env is also not required becuase it is already imported on the root composer